name: Run Semantic Release

on:
    workflow_call:

jobs:
    SemanticRelease:
        runs-on: ubuntu-latest
        permissions:
            contents: write # to be able to publish a GitHub release
            issues: write # to be able to comment on released issues
            pull-requests: write # to be able to comment on released pull requests
        steps:
            -   name: Checkout source code
                uses: actions/checkout@v4
                with:
                    token: ${{ secrets.GH_TOKEN }}
            -   name: GitHub Release
                uses: actions/setup-node@v4
                run: npx semantic-release
                working-directory: src/WebAPI/ClientApp/
                with:
                    node-version: 21
                env:
                    GH_TOKEN: ${{ secrets.GH_TOKEN }}
                    GIT_AUTHOR_NAME: ${{ vars.GIT_AUTHOR_NAME }}
                    GIT_AUTHOR_EMAIL: ${{ vars.GIT_AUTHOR_EMAIL }}
                    GIT_COMMITTER_NAME: ${{ vars.GIT_COMMITTER_NAME }}
                    GIT_COMMITTER_EMAIL: ${{ vars.GIT_COMMITTER_EMAIL }}
